In [0]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

In [0]:
dataset=load_iris()

X=dataset.data
y=dataset.target

x_train, x_test, y_train, y_test=train_test_split(X, y, test_size=0.2)

print(x_test.shape)
print(x_train.shape)



(30, 4)
(120, 4)


In [0]:
sc=StandardScaler()
X = sc.fit_transform(X)

In [0]:
model=GaussianNB()
model.fit(x_train, y_train)
y_pred=model.predict(x_test)
print(accuracy_score(y_test, y_pred))
print(model.score(x_test, y_test))

1.0
1.0


In [0]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('Score:',model.score(x_test,y_test))

[[10  0  0]
 [ 0 13  0]
 [ 0  0  7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         7

   micro avg       1.00      1.00      1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Score: 1.0
