In [0]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [3]:
iris=datasets.load_iris()
X=iris.data[:, :2]
y=iris.target

print(X.shape)

x_train, x_test, y_train, y_test=train_test_split(X, y)
print(x_train.shape)
print(x_test.shape)

model=MLPClassifier(hidden_layer_sizes=(256, 128, 64), max_iter=100000, activation="relu", alpha=0.0001,  solver='sgd')
model.fit(x_train, y_train)
y_pred=model.predict(x_test)
print("Accuracy: ",(accuracy_score(y_test, y_pred))*100)
cm=confusion_matrix(y_test, y_pred)
print(cm)



(150, 2)
(112, 2)
(38, 2)
Accuracy:  68.42105263157895
[[ 9  0  0]
 [ 0  6  7]
 [ 0  5 11]]
