In [0]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

In [0]:
dataset=load_iris()

X=dataset.data
y=dataset.target

x_train, x_test, y_train, y_test=train_test_split(X, y, test_size=0.2)

print(x_test.shape)
print(x_train.shape)

(30, 4)
(120, 4)


In [0]:
sc=StandardScaler()
X = sc.fit_transform(X)

In [0]:
model=BernoulliNB()
model.fit(x_train, y_train)
y_pred=model.predict(x_test)
print(accuracy_score(y_test, y_pred))
print(model.score(x_test, y_test))

0.3
0.3


In [0]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('Score:',model.score(x_test,y_test))

[[ 9  0  0]
 [12  0  0]
 [ 9  0  0]]
              precision    recall  f1-score   support

           0       0.30      1.00      0.46         9
           1       0.00      0.00      0.00        12
           2       0.00      0.00      0.00         9

   micro avg       0.30      0.30      0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30

Score: 0.3


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
